version: 2

jobs:

  build:

    docker:

      - image: circleci/openjdk:8u222-stretch

    steps:

      - checkout


      - run:

          name: Install CxCLI Plugin

          command: |

            wget -O ~/cxcli.zip https://download.checkmarx.com/8.9.0/Plugins/CxConsolePlugin-8.90.0.zip

            unzip ~/cxcli.zip -d ~/cxcli

            chmod +x ~/cxcli/runCxConsole.sh

      - run:

          name: Teste Variaveis de ambiente
          
          command: |
          
            echo $CX_PASSWORD $CX_TEAM $CX_PROJECT $CX_SERVER $CX_USER


      - run:

          name: Execute CxSAST Scan

          command: |

            ~/cxcli/runCxConsole.sh Scan -v -Projectname "$CX_TEAM\\$CX_PROJECT" -CxServer $CX_SERVER -cxuser $CX_USER -cxpassword $CX_PASSWORD -locationtype folder -locationpath $CIRCLE_WORKING_DIRECTORY -preset All -SASTHigh 0 -SASTMedium 0 -SASTLow 0 -ReportXML $CX_PROJECT-results.xml -ReportPDF $CX_PROJECT-results.pdf

 

      - run:

          name: Moving Artifacts

          command: |

            mkdir ~/artifacts

            mv ~/cxcli/$CX_PROJECT/* ~/artifacts

 

      # Store the generated reports with the build logs in CircleCI

      - store_artifacts:

          path: ~/artifacts

          destination: sast_results
