version: 2

jobs:

  build:

    docker:

      - image: circleci/openjdk:8u222-stretch

    steps:

      - checkout


      - run:

          name: Install CxCLI Plugin

          command: |

            wget -O ~/cxcli.zip https://download.checkmarx.com/8.9.0/Plugins/CxConsolePlugin-8.90.0.zip

            unzip ~/cxcli.zip -d ~/cxcli

            chmod +x ~/cxcli/runCxConsole.sh

      - run:

          name: Teste Variaveis de ambiente
          
          command: |
          
            echo $CX_PASSWORD $CX_TEAM $CX_PROJECT $CX_SERVER $CX_USER
            
      - run:

          name: Folder List
          
          command: |
          
            ls


      - run:

          name: Execute CxSAST Scan

          command: |

            ~/cxcli/runCxConsole.sh Scan -v -Projectname "CxServer\SP\Company\Users\CircleCI" -CxServer http://187.18.61.191 -cxuser admin -cxpassword Admin.123 -locationtype folder -locationpath $CIRCLE_WORKING_DIRECTORY -preset Default

 

      - run:

          name: Moving Artifacts

          command: |

            mkdir ~/artifacts

            mv ~/cxcli/$CX_PROJECT/* ~/artifacts

 

      # Store the generated reports with the build logs in CircleCI

      - store_artifacts:

          path: ~/artifacts

          destination: sast_results
